// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFdlqW6-3wIEBWGJ-pvamOorE8ehnw4U',
    appId: '1:135516471154:web:07ead3d1d629c8711867eb',
    messagingSenderId: '135516471154',
    projectId: 'agencysn-a133f',
    authDomain: 'agencysn-a133f.firebaseapp.com',
    storageBucket: 'agencysn-a133f.appspot.com',
    measurementId: 'G-EVFLZGSQGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8CNbyzkCz40KfFK6ZIex0hLq8H8Vlw8',
    appId: '1:135516471154:android:d570e7b3f9612e6c1867eb',
    messagingSenderId: '135516471154',
    projectId: 'agencysn-a133f',
    storageBucket: 'agencysn-a133f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Byn2-R5GZgsMX8tb_ZsRm63tGG6sRQo',
    appId: '1:135516471154:ios:3d7f19bd67249c3e1867eb',
    messagingSenderId: '135516471154',
    projectId: 'agencysn-a133f',
    storageBucket: 'agencysn-a133f.appspot.com',
    iosBundleId: 'com.agencysn.agencysn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Byn2-R5GZgsMX8tb_ZsRm63tGG6sRQo',
    appId: '1:135516471154:ios:3d7f19bd67249c3e1867eb',
    messagingSenderId: '135516471154',
    projectId: 'agencysn-a133f',
    storageBucket: 'agencysn-a133f.appspot.com',
    iosBundleId: 'com.agencysn.agencysn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgFdlqW6-3wIEBWGJ-pvamOorE8ehnw4U',
    appId: '1:135516471154:web:cfb0830276bc64de1867eb',
    messagingSenderId: '135516471154',
    projectId: 'agencysn-a133f',
    authDomain: 'agencysn-a133f.firebaseapp.com',
    storageBucket: 'agencysn-a133f.appspot.com',
    measurementId: 'G-QBYML79EQH',
  );
}
